version: '2.2'

volumes:
  grafana_data: {}

services:

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    network_mode: host
    ports:
      - 9100:9100

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    network_mode: host
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - ./dashboards:/var/lib/grafana/dashboards
