global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'node-exporter'
    scrape_interval: 10s
    static_configs:
    - targets: ['127.0.0.1:9100']

  - job_name: 'heimdall'
    scrape_interval: 10s
    static_configs:
    - targets: ['127.0.0.1:26660']

  - job_name: 'bor'
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: /debug/metrics/prometheus
    scheme: http
    static_configs:
    - targets: ['127.0.0.1:7071']
